actually do the work

diff --git a/root/etc/s6-overlay/s6-rc.d/init-calibre-web-config/run b/root/etc/s6-overlay/s6-rc.d/init-calibre-web-config/run
--- a/root/etc/s6-overlay/s6-rc.d/init-calibre-web-config/run
+++ b/root/etc/s6-overlay/s6-rc.d/init-calibre-web-config/run
@@ -5,6 +5,20 @@
 rm -rf /etc/ImageMagick-6/policy.xml
 ln -s /defaults/policy.xml /etc/ImageMagick-6/policy.xml
 
+# handle app.db updates for kepubify and ext binary path
+# borrowed from crocodilestick because it's a better solution than what i was doing
+sqlite3 /config/app.db <<EOS
+    update settings set config_kepubifypath='/usr/bin/kepubify', config_binariesdir='/usr/bin';
+EOS
+
+if [[ $? == 0 ]]
+then
+    echo "Successfully set binary paths in '/config/app.db'!"
+elif [[ $? > 0 ]]
+then
+    echo "Could not set binary paths for '/config/app.db' (see errors above)."
+fi
+
 # create Google drive client_secrets.json file
 if [[ ! -f /config/client_secrets.json ]]; then
     echo "{}" > /config/client_secrets.json
